name: nlp-mt
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - transformers
      - sentencepiece
      - datasets
      - sacremoses
      - accelerate
      - bitsandbytes
      - sentence-transformers
      - scikit-learn
      - sacrebleu
      - bert-score
      - nltk
      - numpy
      - matplotlib
      - protobuf
      - langchain
      - langchain-huggingface
      - langchain-core
      - unbabel-comet
